# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ONEPIC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ONEPIC

  pod 'Moya', '~> 12.0'

  target 'ONEPICTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ONEPICUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
